[package]
name = "akira-debugger"
version = "0.4.0"
description = "Akira Debugger — real-time desktop app for Laravel Ray logs."
authors = ["Kidiatoliny Gonçalves <kid@akira.io>"]
license = "MIT"
repository = "https://github.com/akira-io/akira-debugger"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.13", features = [] }

[dependencies]
tauri = { version = "2.9", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2.0.0-rc.4"
tokio = { version = "1.40", features = ["full", "sync"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
colored = "3.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12", features = ["json"] }
sha2 = "0.10"
hex = "0.4"
directories = "5.0"
thiserror = "1.0"
aes-gcm = "0.10"
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
